name: Release Documentation

on:
  release:
    types: [published]
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Install Dependencies
        run: pip install mkdocs-material mkdocs-rss-plugin mike
      - name: Deploy docs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mike deploy --push --update-aliases ${{ github.event.release.tag_name }} latest
      - name: Set default
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mike set-default --push latest